import { Metadata } from "next"
import Link from "next/link"
import { Navigation } from "@/components/navigation"
import { Footer } from "@/components/footer"
import { ThemeToggle } from "@/components/theme-toggle"
import Breadcrumbs from "@/components/seo/Breadcrumbs"

const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://novosapien.ai"

export const metadata: Metadata = {
	title: "Terms of Service",
	description:
		"Read Novosapien's terms of service. Understand your rights, obligations, and how we deliver AI workforce solutions for your business.",
	openGraph: {
		type: "website",
		locale: "en_US",
		url: `${baseUrl}/terms`,
		siteName: "Novosapien",
		title: "Terms of Service | Novosapien",
		description:
			"Read our terms of service for using Novosapien's AI workforce platform. Understand your rights and obligations.",
		images: [
			{
				url: "/og-image.png",
				width: 1200,
				height: 630,
				alt: "Novosapien Terms of Service",
			},
		],
	},
	twitter: {
		card: "summary_large_image",
		site: "@novosapien",
		creator: "@novosapien",
		title: "Terms of Service | Novosapien",
		description:
			"Read our terms of service for using Novosapien's AI workforce platform. Understand your rights and obligations.",
		images: ["/og-image.png"],
	},
	alternates: {
		canonical: `${baseUrl}/terms`,
	},
	robots: {
		index: true,
		follow: true,
		googleBot: {
			index: true,
			follow: true,
			"max-image-preview": "large",
			"max-snippet": -1,
		},
	},
}

export default function TermsPage() {
	// Schema markup for SEO
	const schemaData = {
		"@context": "https://schema.org",
		"@type": "WebPage",
		"@id": `${baseUrl}/terms#webpage`,
		url: `${baseUrl}/terms`,
		name: "Terms of Service | Novosapien",
		description:
			"Read Novosapien's terms of service. Understand your rights, obligations, and how we deliver AI workforce solutions for your business.",
		dateModified: new Date().toISOString(),
		breadcrumb: {
			"@type": "BreadcrumbList",
			itemListElement: [
				{
					"@type": "ListItem",
					position: 1,
					name: "Home",
					item: baseUrl,
				},
				{
					"@type": "ListItem",
					position: 2,
					name: "Terms of Service",
					item: `${baseUrl}/terms`,
				},
			],
		},
		publisher: {
			"@type": "Organization",
			name: "Novosapien",
			url: baseUrl,
		},
	}

	// FAQ data for terms questions
	const faqs = [
		{
			question: "What services does Novosapien provide?",
			answer:
				"Novosapien provides AI-powered digital workforce solutions that automate business processes. Our services include pre-built workforces for content creation and lead generation, custom workforce development through our Lab, and ongoing support and optimization.",
		},
		{
			question: "Can I cancel my Novosapien subscription anytime?",
			answer:
				"Yes, you can cancel your subscription at any time. For monthly plans, cancellation takes effect at the end of your current billing period. For annual plans, please refer to your specific agreement terms or contact our support team.",
		},
		{
			question: "Who owns the content generated by AI workforces?",
			answer:
				"You retain full ownership of all content and data generated by our AI workforces for your business. Novosapien claims no ownership rights to your generated content, business data, or any outputs produced by the platform for your use.",
		},
		{
			question: "What happens to my data if I terminate service?",
			answer:
				"Upon termination, you can export all your data within 30 days. After this period, we securely delete your data from our systems, except where legally required to retain it. We provide data export assistance to ensure smooth transition.",
		},
		{
			question: "Are there usage limits on AI workforce operations?",
			answer:
				"Usage limits depend on your subscription plan. Each plan includes specified limits for agent operations, data processing, and API calls. Enterprise plans offer custom limits based on your needs. Exceeding limits may incur additional charges as outlined in your agreement.",
		},
		{
			question: "What support is included with my subscription?",
			answer:
				"All plans include email support and access to our knowledge base. Professional plans add priority support and monthly check-ins. Enterprise plans include dedicated account management, SLA guarantees, and custom training sessions.",
		},
	]

	// FAQ schema for SEO
	const faqSchema = {
		"@context": "https://schema.org",
		"@type": "FAQPage",
		mainEntity: faqs.map(faq => ({
			"@type": "Question",
			name: faq.question,
			acceptedAnswer: {
				"@type": "Answer",
				text: faq.answer,
			},
		})),
	}

	return (
		<>
			{/* Schema Markup */}
			<script
				type="application/ld+json"
				dangerouslySetInnerHTML={{ __html: JSON.stringify(schemaData) }}
			/>
			<script
				type="application/ld+json"
				dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
			/>

			<div className="min-h-screen bg-background">
				{/* Navigation */}
				<Navigation />

				{/* Theme Toggle */}
				<div className="fixed top-4 right-4 z-50 hidden md:block">
					<ThemeToggle />
				</div>

				{/* Breadcrumbs - hidden but present for SEO */}
				<Breadcrumbs
					items={[{ name: "Home", href: "/" }, { name: "Terms of Service" }]}
				/>

				{/* Main Content */}
				<main className="pt-32 pb-24 px-4">
					<div className="max-w-4xl mx-auto">
						{/* Header */}
						<div className="text-center mb-12">
							<h1 className="text-foreground text-6xl md:text-7xl font-light tracking-tight font-geist-sans mb-4">
								Terms of Service
							</h1>
							<p className="text-muted-foreground text-lg">
								Effective Date:{" "}
								{new Date().toLocaleDateString("en-US", {
									month: "long",
									day: "numeric",
									year: "numeric",
								})}
							</p>
						</div>

						{/* Terms Content */}
						<div className="prose prose-lg dark:prose-invert max-w-none space-y-8">
							{/* Agreement to Terms */}
							<section>
								<h2 className="text-2xl font-semibold text-foreground mb-4">
									1. Agreement to Terms
								</h2>
								<p className="text-muted-foreground">
									By accessing or using Novosapien&apos;s AI workforce platform and
									services (&quot;Services&quot;), you agree to be bound by these Terms of
									Service (&quot;Terms&quot;). If you disagree with any part of these
									terms, you may not access our Services.
								</p>
							</section>

							{/* Description of Services */}
							<section>
								<h2 className="text-2xl font-semibold text-foreground mb-4">
									2. Description of Services
								</h2>
								<p className="text-muted-foreground mb-3">
									Novosapien provides AI-powered digital workforce solutions that
									include:
								</p>
								<ul className="list-disc pl-6 space-y-1 text-muted-foreground">
									<li>
										Pre-built AI workforces for content creation and lead
										generation
									</li>
									<li>Custom workforce development through our Lab</li>
									<li>Platform access for managing and monitoring AI agents</li>
									<li>
										Integration capabilities with existing business systems
									</li>
									<li>Support and optimization services</li>
								</ul>
							</section>

							{/* Account Registration */}
							<section>
								<h2 className="text-2xl font-semibold text-foreground mb-4">
									3. Account Registration
								</h2>
								<p className="text-muted-foreground">
									To use our Services, you must create an account. You agree to provide accurate, current, and complete information during registration and to update such information to keep it accurate. You are responsible for safeguarding your account credentials and for all activities that occur under your account.
								</p>
							</section>

							{/* Acceptable Use */}
							<section>
								<h2 className="text-2xl font-semibold text-foreground mb-4">4. Acceptable Use Policy</h2>
								<p className="text-muted-foreground mb-3">
									You agree not to use our Services to:
								</p>
								<ul className="list-disc pl-6 space-y-1 text-muted-foreground">
									<li>Violate any laws or regulations</li>
									<li>Infringe upon intellectual property rights</li>
									<li>Generate harmful, offensive, or misleading content</li>
									<li>Attempt to gain unauthorized access to our systems</li>
									<li>Interfere with or disrupt the Services</li>
									<li>Use the Services for any illegal or unauthorized purpose</li>
								</ul>
							</section>

							{/* Intellectual Property */}
							<section>
								<h2 className="text-2xl font-semibold text-foreground mb-4">5. Intellectual Property Rights</h2>
								<div className="space-y-3">
									<div>
										<h3 className="text-xl font-medium text-foreground mb-2">Our Property</h3>
										<p className="text-muted-foreground">
											The Services, including all software, technology, designs, and content provided by Novosapien, are owned by us and protected by intellectual property laws. You may not copy, modify, or reverse engineer any part of our Services.
										</p>
									</div>
									<div>
										<h3 className="text-xl font-medium text-foreground mb-2">Your Content</h3>
										<p className="text-muted-foreground">
											You retain ownership of all content you provide to the Services and all output generated for you. You grant us a limited license to use your content solely to provide the Services to you.
										</p>
									</div>
								</div>
							</section>

							{/* Payment Terms */}
							<section>
								<h2 className="text-2xl font-semibold text-foreground mb-4">6. Payment and Billing</h2>
								<p className="text-muted-foreground">
									Paid Services are billed in advance on a subscription basis. You agree to pay all fees according to your selected plan. Fees are non-refundable except as required by law or as explicitly stated in these Terms. We reserve the right to modify pricing with 30 days' notice.
								</p>
							</section>

							{/* Termination */}
							<section>
								<h2 className="text-2xl font-semibold text-foreground mb-4">7. Termination</h2>
								<p className="text-muted-foreground">
									Either party may terminate these Terms at any time. You may cancel your account through your account settings or by contacting support. We may suspend or terminate your access for violations of these Terms. Upon termination, your right to use the Services ceases immediately.
								</p>
							</section>

							{/* Disclaimers */}
							<section>
								<h2 className="text-2xl font-semibold text-foreground mb-4">8. Disclaimers and Limitations</h2>
								<p className="text-muted-foreground">
									The Services are provided "as is" without warranties of any kind. We do not guarantee that the Services will be uninterrupted or error-free. Our total liability shall not exceed the amount you paid us in the twelve months preceding the claim. We are not liable for indirect, incidental, or consequential damages.
								</p>
							</section>

							{/* Indemnification */}
							<section>
								<h2 className="text-2xl font-semibold text-foreground mb-4">9. Indemnification</h2>
								<p className="text-muted-foreground">
									You agree to indemnify and hold harmless Novosapien and its affiliates from any claims, damages, losses, and expenses arising from your use of the Services, violation of these Terms, or infringement of any third-party rights.
								</p>
							</section>

							{/* Governing Law */}
							<section>
								<h2 className="text-2xl font-semibold text-foreground mb-4">10. Governing Law</h2>
								<p className="text-muted-foreground">
									These Terms are governed by the laws of the United States and the State of Delaware, without regard to conflict of law principles. Any disputes shall be resolved in the courts of Delaware.
								</p>
							</section>

							{/* Changes to Terms */}
							<section>
								<h2 className="text-2xl font-semibold text-foreground mb-4">11. Changes to Terms</h2>
								<p className="text-muted-foreground">
									We reserve the right to modify these Terms at any time. We will notify you of material changes via email or through the Services. Your continued use of the Services after changes constitutes acceptance of the modified Terms.
								</p>
							</section>

							{/* Contact Information */}
							<section>
								<h2 className="text-2xl font-semibold text-foreground mb-4">12. Contact Information</h2>
								<p className="text-muted-foreground">
									If you have questions about these Terms of Service, please contact us at:
								</p>
								<div className="mt-3 space-y-1 text-muted-foreground">
									<p>Email: legal@novosapien.ai</p>
									<p>Address: Novosapien, Inc.</p>
								</div>
							</section>
						</div>

						{/* FAQ Section */}
						<section className="mt-16">
							<h2 className="text-2xl font-semibold text-foreground mb-8 text-center">
								Frequently Asked Questions
							</h2>
							<div className="space-y-4">
								{faqs.map((faq, index) => (
									<details
										key={index}
										className="group bg-card-background border border-accent/20 rounded-lg"
									>
										<summary className="flex items-center justify-between p-6 cursor-pointer hover:bg-accent/5 transition-colors">
											<h3 className="text-foreground text-lg font-medium pr-4">
												{faq.question}
											</h3>
											<svg
												className="w-5 h-5 text-muted-foreground transition-transform duration-200 group-open:rotate-180"
												fill="none"
												viewBox="0 0 24 24"
												stroke="currentColor"
												aria-hidden="true"
											>
												<path
													strokeLinecap="round"
													strokeLinejoin="round"
													strokeWidth={2}
													d="M19 9l-7 7-7-7"
												/>
											</svg>
										</summary>
										<div className="px-6 pb-6">
											<p className="text-muted-foreground">{faq.answer}</p>
										</div>
									</details>
								))}
							</div>
						</section>

						{/* Related Links Section */}
						<section className="mt-16 pt-8 border-t border-accent/20">
							<h2 className="text-2xl font-semibold text-foreground mb-6 text-center">
								Related Policies
							</h2>
							<div className="grid grid-cols-1 md:grid-cols-2 gap-6">
								<Link
									href="/privacy"
									className="block p-6 bg-card-background border border-accent/20 rounded-lg hover:shadow-lg hover:border-accent/40 transition-all"
								>
									<h3 className="text-xl font-semibold text-foreground mb-2">
										Privacy Policy
									</h3>
									<p className="text-muted-foreground">
										Understand how we collect, use, and protect your personal information.
									</p>
									<span className="text-primary-blue mt-2 inline-block font-medium">
										Read Privacy Policy →
									</span>
								</Link>
								<Link
									href="/cookies"
									className="block p-6 bg-card-background border border-accent/20 rounded-lg hover:shadow-lg hover:border-accent/40 transition-all"
								>
									<h3 className="text-xl font-semibold text-foreground mb-2">
										Cookie Policy
									</h3>
									<p className="text-muted-foreground">
										Learn about our use of cookies and tracking technologies.
									</p>
									<span className="text-primary-blue mt-2 inline-block font-medium">
										View Cookie Policy →
									</span>
								</Link>
							</div>
						</section>
					</div>
				</main>

				{/* Footer */}
				<Footer />
			</div>
		</>
	)
}